# -*- coding: utf-8 -*-
"""2DpinnsRectangular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpbMr_TVARFG95_GLuNqSTlWUhRX4-VZ
"""



!pip install deepxde
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import matplotlib.pyplot as plt
import numpy as np
import deepxde as dde
from deepxde.backend import tf
from google.colab import files
import pandas as pd
import os
dde.config.set_random_seed(42)
dde.config.real.set_float32()

dim_input = 3
dim_output = 3

Time = 2.0

X_min = 0.0
X_max = 100.0
Y_min = 0.0
Y_max = 100.0
X_0 = 50.0

g = 9.81


def on_initial(_, on_initial):
    return on_initial

def boundary_x1(x, on_boundary):
    return on_boundary and np.isclose(x[0], X_min)

def boundary_x2(x, on_boundary):
    return on_boundary and np.isclose(x[0], X_max)
def boundary_y1(x, on_boundary):
    return on_boundary and np.isclose(x[1], Y_min)

def boundary_y2(x, on_boundary):
    return on_boundary and np.isclose(x[1], Y_max)
# def func_IC_h(x):
#     h_r = 1.0  # Height on the right side
#     h_l = 0.02  # Height on the left side
#     return np.where(x[:, 0:1] <= X_0, h_r, h_l)

def func_IC_h(x):
    # Define the rectangle's boundaries
    rect_x_min = 30.0  # Rectangle lower bound in X-direction
    rect_x_max = 70.0  # Rectangle upper bound in X-direction
    rect_y_min = 30.0  # Rectangle lower bound in Y-direction
    rect_y_max = 70.0  # Rectangle upper bound in Y-direction

    # Set height inside the rectangle and outside
    inside_rectangle = (x[:, 0:1] >= rect_x_min) & (x[:, 0:1] <= rect_x_max) & \
                       (x[:, 1:2] >= rect_y_min) & (x[:, 1:2] <= rect_y_max)

    # Return 10.0 inside the rectangle, and 1.0 outside it
    return 5.0 * inside_rectangle + 0.2 * ~inside_rectangle

# Create a meshgrid for plotting
N = 501
X_plot, Y_plot = np.meshgrid(np.linspace(0, 100, N), np.linspace(0, 100, N))
X_flat = X_plot.flatten()
Y_flat = Y_plot.flatten()
T_flat = np.zeros_like(X_flat)  # Assuming t=0 for the initial condition
Q_plot = np.column_stack((X_flat, Y_flat, T_flat))
h_plot = func_IC_h(Q_plot).reshape(N, N)

# # Plot the initial condition with a surface plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(X_plot, Y_plot, h_plot, cmap='viridis')
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Water Surface Height')
ax.set_title('Rectangular Dam Break Initial Condition')
plt.show()


def func_IC_u(x):
  return np.zeros([len(x), 1])

def func_IC_v(x):
  return np.zeros([len(x), 1])

def func_BC_all(x):
  return np.zeros([len(x), 1])

def pde(x, y):
    h = y[:, 0:1]
    u = y[:, 1:2]
    v = y[:, 2:3]

    U1 = h
    U2 = h * u
    U3 = h * v

    E1 = h * u
    E2 = h * u * u + 0.5 * h * h * g
    E3 = h * u * v

    G1 = h * v
    G2 = h * v * u
    G3 = h * v * v + 0.5 * h*h * g

    E1_x = tf.gradients(E1, x)[0][:, 0:1]
    E2_x = tf.gradients(E2, x)[0][:, 0:1]
    E3_x = tf.gradients(E3, x)[0][:, 0:1]

    G1_y = tf.gradients(G1, x)[0][:, 1:2]
    G2_y = tf.gradients(G2, x)[0][:, 1:2]
    G3_y = tf.gradients(G3, x)[0][:, 1:2]

    U1_t = tf.gradients(U1, x)[0][:, 2:3]
    U2_t = tf.gradients(U2, x)[0][:, 2:3]
    U3_t = tf.gradients(U3, x)[0][:, 2:3]

    equaz_1 = U1_t + E1_x + G1_y
    equaz_2 = U2_t + E2_x + G2_y
    equaz_3 = U3_t + E3_x + G3_y

    return [equaz_1, equaz_2, equaz_3]

# Modify boundary conditions accordingly

geom = dde.geometry.Rectangle([X_min, Y_min],[X_max, Y_max])
timedomain = dde.geometry.TimeDomain(0.0, Time)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

IC_h = dde.IC(geomtime, func_IC_h, on_initial, component = 0)
IC_u = dde.IC(geomtime, func_IC_u, on_initial, component = 1)
IC_v = dde.IC(geomtime, func_IC_v, on_initial, component = 2)

BC_u1 = dde.DirichletBC(geomtime, func_BC_all,
boundary_x1, component = 1)
BC_u2 = dde.DirichletBC(geomtime, func_BC_all,
boundary_x2, component = 1)
BC_v1 = dde.DirichletBC(geomtime, func_BC_all,
boundary_y1, component = 2)
BC_v2 = dde.DirichletBC(geomtime, func_BC_all,
boundary_y2, component = 2)

IC_BC = [IC_h, IC_u, IC_v, BC_u1, BC_u2, BC_v1, BC_v2]

data = dde.data.TimePDE(
    geomtime, pde, IC_BC,
    num_domain=25000,
    num_boundary=10000,
    num_initial=25000)

net = dde.maps.FNN(
    layer_sizes=[dim_input] + [100] * 5 + [dim_output],
    activation="tanh",
    kernel_initializer="Glorot uniform")
#net.apply_output_transform(lambda x, y: func_IC_h_circular(x,y))
os.makedirs("solution_outputs_rec", exist_ok=True)
model = dde.Model(data, net)

model.compile('adam', lr=0.0001)
# Train the model and capture the training history
losshistory, train_state = model.train(iterations=20000)
loss_train = losshistory.loss_train

# Compute total loss by summing all components at each epoch
total_loss = [sum(l) for l in loss_train]
df = pd.DataFrame({"Step": range(1, len(total_loss)+1), "Loss": total_loss})
df.to_csv("solution_outputs_rec/training_loss_rec.csv", index=False, header=False)

plt.figure()
plt.semilogy(total_loss, color='red', label="Training Loss (Tanh Activation)")
plt.xlabel("# Steps")
plt.ylabel("Loss")
plt.title("Loss History")
plt.legend()
plt.tight_layout()
plt.savefig("solution_outputs_rec/training_loss_rec.png", dpi=300)
plt.close()

plot_Time = [0.0, 0.5, 0.8, 1.0, 1.5, 2.0]


N_x = 501
N_y =501

X_plot, Y_plot = np.meshgrid(np.linspace(X_min, X_max, N_x), np.linspace(Y_min, Y_max, N_y))
X_plot = X_plot.flatten()
Y_plot = Y_plot.flatten()

# for i, dummy in enumerate(plot_Time):
#     T_plot = np.ones_like(X_plot) * plot_Time[i]

#     Q_plot = np.column_stack((X_plot, Y_plot, T_plot))
#     W_plot = model.predict(Q_plot)
#     Z_plot = W_plot[:, 0]

#     Z_plot = np.reshape(Z_plot, (N_y, N_x))
#     if i % 40 == 0:  # Plot every 10th time step

#     # Plotting the contour plot
#         fig=plt.figure()
#         ax = fig.add_subplot(111, projection='3d')
#         ax.plot_surface(X_plot.reshape(N_y, N_x), Y_plot.reshape(N_y, N_x), Z_plot, cmap="viridis")
#         ax.set_xlabel('X')
#         ax.set_ylabel('Y')
#         ax.set_zlabel('Water Surface Height')
#         ax.set_title(r'T $= {:.2f}$ [s]'.format(plot_Time[i]))
#         plt.show()


for t in plot_Time:  # Loop over the time steps
    T_plot = np.ones_like(X_plot) * t
    Q_plot = np.column_stack((X_plot, Y_plot, T_plot))
    W_plot = model.predict(Q_plot)
    Z_plot = W_plot[:, 0]  # Water surface height (h)
    Z_plot = np.reshape(Z_plot, (N_y, N_x))  # Reshape to 2D grid for plotting
    pd.DataFrame(Z_plot).to_csv(f"solution_outputs_rec/height_rectangle_t{t:.2f}.csv", index=False, header=False)

    # Create a figure with two subplots
    fig = plt.figure(figsize=(14, 6))

    # 3D Surface plot on the left
    ax_surface = fig.add_subplot(121, projection='3d')
    ax_surface.plot_surface(X_plot.reshape(N_y, N_x), Y_plot.reshape(N_y, N_x), Z_plot, cmap='viridis')
    ax_surface.set_xlabel('X')
    ax_surface.set_ylabel('Y')
    ax_surface.set_zlabel('Water Height')
    ax_surface.set_title(f'3D Surface at T = {t:.2f} s')

    # Contour (Heat map) plot on the right
    ax_contour = fig.add_subplot(122)
    heatmap = ax_contour.imshow(Z_plot, origin='lower', cmap='viridis', aspect='auto', extent=[X_min, X_max, Y_min, Y_max]) # Added extent
    ax_contour.set_xlabel('X')
    ax_contour.set_ylabel('Y')
    ax_contour.set_title(f'Contour Plot at T = {t:.2f} s')
    plt.colorbar(heatmap, ax=ax_contour, label='Water Height')

    plt.tight_layout()
    plt.show()
