# -*- coding: utf-8 -*-
"""SW2Dcicular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVFQVniAEudjUVqT38988E7QsqWL9KKW
"""

!pip install deepxde
import matplotlib.pyplot as plt
import numpy as np
import deepxde as dde
from deepxde.backend import tf
from google.colab import files
from scipy.interpolate import RegularGridInterpolator
dde.config.set_random_seed(42)
dde.config.real.set_float32()

uploaded = files.upload()
# Load the numerical data from the .npz file
# Load the numerical data
h_numerical = np.load("h_numerical.npy")  # Shape (4, 401, 401)
time_numerical = np.linspace(0.0, 0.4, 4)  # Assuming 4 time steps for 0 to 0.4 seconds
x_numerical = np.linspace(0.0, 100.0, 401)
y_numerical = np.linspace(0.0, 100.0, 401)

# Create an interpolator
interpolator = RegularGridInterpolator(
    (time_numerical, x_numerical, y_numerical), h_numerical, bounds_error=False, fill_value=None
)

dim_input = 3
dim_output = 3

scale_h = 1000.0

Time = 2.0

X_min = 0.0
X_max = 100.0
Y_min = 0.0
Y_max = 100.0
X_0 = 50.0
g = 9.81

def on_initial(_, on_initial):
    return on_initial

def boundary_x1(x, on_boundary):
    return on_boundary and np.isclose(x[0], X_min)

def boundary_x2(x, on_boundary):
    return on_boundary and np.isclose(x[0], X_max)

def boundary_y1(x, on_boundary):
    return on_boundary and np.isclose(x[1], Y_min)

def boundary_y2(x, on_boundary):
    return on_boundary and np.isclose(x[1], Y_max)

def func_IC_h(x):
    t = x[:, 2]  # Extract time
    points = np.column_stack((t, x[:, 0], x[:, 1]))
    h_interp = interpolator(points)
    return np.expand_dims(h_interp, axis=1)

def func_IC_u(x):
    return np.zeros([len(x), 1])

def func_IC_v(x):
    return np.zeros([len(x), 1])

def func_BC_all(x):
    return np.zeros([len(x), 1])

def pde(x, y):
    h = y[:, 0:1]
    u = y[:, 1:2]
    v = y[:, 2:3]

    U1 = h
    U2 = h * u
    U3 = h * v

    E1 = h * u
    E2 = h * u * u + 0.5 * h * h * g
    E3 = h * u * v

    G1 = h * v
    G2 = h * v * u
    G3 = h * v * v + 0.5 * h*h * g

    E1_x = tf.gradients(E1, x)[0][:, 0:1]
    E2_x = tf.gradients(E2, x)[0][:, 0:1]
    E3_x = tf.gradients(E3, x)[0][:, 0:1]

    G1_y = tf.gradients(G1, x)[0][:, 1:2]
    G2_y = tf.gradients(G2, x)[0][:, 1:2]
    G3_y = tf.gradients(G3, x)[0][:, 1:2]

    U1_t = tf.gradients(U1, x)[0][:, 2:3]
    U2_t = tf.gradients(U2, x)[0][:, 2:3]
    U3_t = tf.gradients(U3, x)[0][:, 2:3]

    equaz_1 = U1_t + E1_x + G1_y
    equaz_2 = U2_t + E2_x + G2_y
    equaz_3 = U3_t + E3_x + G3_y

    return [equaz_1, equaz_2, equaz_3]

# Create a meshgrid for plotting
# Create a meshgrid for plotting with the correct dimensions
N = 401  # Change N to match the dimensions of t0_data
X_plot, Y_plot = np.meshgrid(np.linspace(0, 100, N), np.linspace(0, 100, N))
X_flat = X_plot.flatten()
Y_flat = Y_plot.flatten()
T_flat = np.zeros_like(X_flat)  # Assuming t=0 for the initial condition
Q_plot = np.column_stack((X_flat, Y_flat, T_flat))

# Use the original shape of t0_data when reshaping:
h_plot = func_IC_h(Q_plot) # Reshape to t0_data's shape (401, 401)
h_plot = h_plot.reshape(X_plot.shape)
# Plot the initial condition with a surface plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(X_plot, Y_plot, h_plot, cmap='viridis') # Use X_plot,Y_plot with dimensions (401,401)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Water Surface Height')
ax.set_title('Dam Break Initial Condition at t = 0')
plt.show()
# Modify boundary conditions accordingly
geom = dde.geometry.Rectangle([X_min, Y_min],[X_max, Y_max])
timedomain = dde.geometry.TimeDomain(0.0, Time)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

IC_h = dde.IC(geomtime, func_IC_h, lambda x, _: x[2] <= 0.4, component=0)

IC_u = dde.IC(geomtime, func_IC_u, on_initial, component = 1)
IC_v = dde.IC(geomtime, func_IC_v, on_initial, component = 2)

BC_u1 = dde.DirichletBC(geomtime, func_BC_all, boundary_x1, component = 1)
BC_u2 = dde.DirichletBC(geomtime, func_BC_all, boundary_x2, component = 1)
BC_v1 = dde.DirichletBC(geomtime, func_BC_all, boundary_y1, component = 2)
BC_v2 = dde.DirichletBC(geomtime, func_BC_all, boundary_y2, component = 2)

IC_BC = [IC_h, IC_u, IC_v, BC_u1, BC_u2, BC_v1, BC_v2]

# Create the TimePDE data object
data = dde.data.TimePDE(
    geomtime, pde, IC_BC,
    num_domain=20000,
    num_boundary=1000,
    num_initial=20000)

# Define the neural network model
net = dde.maps.FNN(
    layer_sizes=[dim_input] + [100] * 5 + [dim_output],
    activation="tanh",
    kernel_initializer="Glorot uniform")

model = dde.Model(data, net)

# Compile the model using the Adam optimizer
model.compile('adam', lr=0.0001)

# Train the model and capture the training history
losshistory, train_state = model.train(iterations=16000)

# Plot the loss history
dde.utils.plot_loss_history(losshistory)
plt.title("Loss History")
plt.show()

# Visualization: Plot the predictions for future time steps
N_x = 401
N_y = 401

# Plot for Side-by-Side Surface (2D) and Cross-section (1D)
cross_section_y = 50.0  # Example: Fix Y = 50

X_line = np.linspace(X_min, X_max, N_x)
Y_fixed = np.ones_like(X_line) * cross_section_y

X_plot, Y_plot = np.meshgrid(np.linspace(X_min, X_max, N_x), np.linspace(Y_min, Y_max, N_y))
X_flat = X_plot.flatten()
Y_flat = Y_plot.flatten()

plot_Time = np.linspace(0.0, Time, 2001)

for i, _ in enumerate(plot_Time):
    T_plot = np.ones_like(X_flat) * plot_Time[i]
    Q_plot = np.column_stack((X_flat, Y_flat, T_plot))
    W_plot = model.predict(Q_plot)
    Z_plot = W_plot[:, 0]
    Z_plot = np.reshape(Z_plot, (N_y, N_x))

    if i % 100 == 0:
        fig = plt.figure(figsize=(14, 6))

        ax_surface = fig.add_subplot(121, projection='3d')
        ax_surface.plot_surface(X_plot.reshape(N_y, N_x), Y_plot.reshape(N_y, N_x), Z_plot, cmap='viridis')
        ax_surface.set_xlabel('X')
        ax_surface.set_ylabel('Y')
        ax_surface.set_zlabel('Water Height')
        ax_surface.set_title(f'3D Surface at T = {plot_Time[i]:.2f} s')

        ax_contour = fig.add_subplot(122)
        heatmap = ax_contour.imshow(Z_plot, origin='lower', cmap='viridis', aspect='auto', extent=[X_min, X_max, Y_min, Y_max])
        ax_contour.set_xlabel('X')
        ax_contour.set_ylabel('Y')
        ax_contour.set_title(f'Contour Plot at T = {plot_Time[i]:.2f} s')
        plt.colorbar(heatmap, ax=ax_contour, label='Water Height')

        plt.tight_layout()
        plt.show()